name = "JADE191"
uuid = "88b945bd-a01d-411e-bd47-251d4bf0155a"
authors = ["kevkevs <22803504+kevkevs@users.noreply.github.com> and contributors"]
version = "0.1.0"

[compat]
julia = "1.8"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
